//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from OAL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IOALListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class OALBaseListener : IOALListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.lines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLines([NotNull] OALParser.LinesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.lines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLines([NotNull] OALParser.LinesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] OALParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] OALParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.commands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommands([NotNull] OALParser.CommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.commands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommands([NotNull] OALParser.CommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.parCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParCommand([NotNull] OALParser.ParCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.parCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParCommand([NotNull] OALParser.ParCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.threadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThreadCommand([NotNull] OALParser.ThreadCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.threadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThreadCommand([NotNull] OALParser.ThreadCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfCommand([NotNull] OALParser.IfCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.ifCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfCommand([NotNull] OALParser.IfCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.elif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElif([NotNull] OALParser.ElifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.elif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElif([NotNull] OALParser.ElifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseBlock([NotNull] OALParser.ElseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.elseBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseBlock([NotNull] OALParser.ElseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] OALParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] OALParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.whileCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileCommand([NotNull] OALParser.WhileCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.whileCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileCommand([NotNull] OALParser.WhileCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.foreachCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachCommand([NotNull] OALParser.ForeachCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.foreachCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachCommand([NotNull] OALParser.ForeachCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.continueCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueCommand([NotNull] OALParser.ContinueCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.continueCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueCommand([NotNull] OALParser.ContinueCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.breakCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakCommand([NotNull] OALParser.BreakCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.breakCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakCommand([NotNull] OALParser.BreakCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.commentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentCommand([NotNull] OALParser.CommentCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.commentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentCommand([NotNull] OALParser.CommentCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandQueryCreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandQueryCreate([NotNull] OALParser.ExeCommandQueryCreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandQueryCreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandQueryCreate([NotNull] OALParser.ExeCommandQueryCreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandQueryDelete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandQueryDelete([NotNull] OALParser.ExeCommandQueryDeleteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandQueryDelete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandQueryDelete([NotNull] OALParser.ExeCommandQueryDeleteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandAssignment([NotNull] OALParser.ExeCommandAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandAssignment([NotNull] OALParser.ExeCommandAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandCall([NotNull] OALParser.ExeCommandCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandCall([NotNull] OALParser.ExeCommandCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandCreateList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandCreateList([NotNull] OALParser.ExeCommandCreateListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandCreateList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandCreateList([NotNull] OALParser.ExeCommandCreateListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.listLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListLiteral([NotNull] OALParser.ListLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.listLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListLiteral([NotNull] OALParser.ListLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandAddingToList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandAddingToList([NotNull] OALParser.ExeCommandAddingToListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandAddingToList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandAddingToList([NotNull] OALParser.ExeCommandAddingToListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandRemovingFromList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandRemovingFromList([NotNull] OALParser.ExeCommandRemovingFromListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandRemovingFromList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandRemovingFromList([NotNull] OALParser.ExeCommandRemovingFromListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandWrite([NotNull] OALParser.ExeCommandWriteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandWrite([NotNull] OALParser.ExeCommandWriteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandRead([NotNull] OALParser.ExeCommandReadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandRead([NotNull] OALParser.ExeCommandReadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandWait"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandWait([NotNull] OALParser.ExeCommandWaitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandWait"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandWait([NotNull] OALParser.ExeCommandWaitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandFileCheck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandFileCheck([NotNull] OALParser.ExeCommandFileCheckContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandFileCheck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandFileCheck([NotNull] OALParser.ExeCommandFileCheckContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandFileRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandFileRead([NotNull] OALParser.ExeCommandFileReadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandFileRead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandFileRead([NotNull] OALParser.ExeCommandFileReadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandFileAppend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandFileAppend([NotNull] OALParser.ExeCommandFileAppendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandFileAppend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandFileAppend([NotNull] OALParser.ExeCommandFileAppendContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.exeCommandFileWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExeCommandFileWrite([NotNull] OALParser.ExeCommandFileWriteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.exeCommandFileWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExeCommandFileWrite([NotNull] OALParser.ExeCommandFileWriteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.returnCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnCommand([NotNull] OALParser.ReturnCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.returnCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnCommand([NotNull] OALParser.ReturnCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] OALParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] OALParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.accessChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessChain([NotNull] OALParser.AccessChainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.accessChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessChain([NotNull] OALParser.AccessChainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.accessChainPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessChainPrefix([NotNull] OALParser.AccessChainPrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.accessChainPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessChainPrefix([NotNull] OALParser.AccessChainPrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.accessChainElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessChainElement([NotNull] OALParser.AccessChainElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.accessChainElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessChainElement([NotNull] OALParser.AccessChainElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] OALParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] OALParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] OALParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] OALParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.parameterListSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterListSuffix([NotNull] OALParser.ParameterListSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.parameterListSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterListSuffix([NotNull] OALParser.ParameterListSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.bracketedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracketedExpr([NotNull] OALParser.BracketedExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.bracketedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracketedExpr([NotNull] OALParser.BracketedExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] OALParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] OALParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] OALParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] OALParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] OALParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] OALParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableName([NotNull] OALParser.VariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableName([NotNull] OALParser.VariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodName([NotNull] OALParser.MethodNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.methodName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodName([NotNull] OALParser.MethodNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] OALParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] OALParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OALParser.pragmaCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaCommand([NotNull] OALParser.PragmaCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OALParser.pragmaCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaCommand([NotNull] OALParser.PragmaCommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
